In [3]:
from azure.data.tables import TableServiceClient, UpdateMode
import pandas as pd
import os
import dotenv

# Load environment variables
dotenv.load_dotenv()

True

In [4]:
def read_table_to_dataframe(connection_string, table_name):
    table_service = TableServiceClient.from_connection_string(conn_str=connection_string)
    table_client = table_service.get_table_client(table_name)
    
    # Query all entities in the table
    entities = table_client.list_entities()
    
    # Convert entities to list of dictionaries
    entity_list = []
    for entity in entities:
        entity_dict = dict(entity)
        entity_list.append(entity_dict)
    
    # Convert list of dictionaries to DataFrame
    df = pd.DataFrame(entity_list)
    return df

In [5]:
read_table_to_dataframe(os.getenv('CONNECTION_STRING'), 'testyahoo')

,PartitionKey,RowKey,Close,High,Low,Open,Volume,Dividends,Stock_Splits
0,partition1,0039a955-26e8-472c-ba99-825b5b3dbf34,402.669281,404.797663,400.342004,402.122283,21021200.0,0.0,0.0
1,partition1,01293750-7b11-43ff-80de-621eb36d6894,441.773743,442.342724,435.934262,437.491453,13582000.0,0.0,0.0
2,partition1,016658e1-a9f3-4102-aae5-5dd6ba5de7e1,327.452118,330.598484,326.578669,328.821842,18381000.0,0.0,0.0
3,partition1,02835d8f-8d39-4b81-a499-e7c7ec142c3f,447.563293,450.128677,439.927063,441.793694,20790000.0,0.0,0.0
4,partition1,02917bc3-04f0-443e-bdfc-2beb820ae2bb,357.844025,359.759639,354.965636,356.722438,25833900.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
1003,partition1,feb63b76-5963-44ba-985a-ace6f816cd40,324.821899,326.737514,313.943530,314.191668,25645500.0,0.0,0.0
1004,partition1,fed75250-f4b8-463a-b890-ae881d98ce21,376.850403,378.023982,373.429099,376.432672,30554400.0,0.0,0.0
1005,partition1,ff68b068-2820-4208-9c0e-8f434397eab0,329.298248,334.280868,329.010431,333.318093,17565500.0,0.0,0.0
1006,partition1,ff948f90-6317-46a2-8d58-4d516b38b821,393.519623,400.275238,388.906269,391.197985,23562500.0,0.0,0.0
1007,partition1,ffd16116-7ac0-4973-ac0d-65176d153060,414.383118,416.000198,403.782230,416.000198,47995300.0,0.0,0.0